# Generated by Django 4.2.15 on 2024-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'open'), ('2', 'close')], max_length=255),
        ),
    ]
